#!/bin/sh

DB_NAME=
WITH_TEST_DATA=false
WITH_PLUGIN_SETUP=false
export PSQL=psql
export SCRIPTSDIR=/usr/share/nz-building-outlines/

usage() {
    echo "Usage: $0 <database> [--with-test-data]" >&2
    echo "Usage: $0 <database> [--with-plugin-setup]" >&2
    echo "Usage: $0 [--version]" >&2
}

# Check that at least one argument has been supplied, if not print usage
if [ -z "$1" ]; then
    usage
    exit 1
fi

# Supporting version and help commands
if test "$1" = "--version"; then
    echo "dev"
    exit 0
fi

if test "$1" = "-v"; then
    echo "dev"
    exit 0
fi

if test "$1" = "--help"; then
    usage
    exit 0
fi

if test "$1" = "-h"; then
    usage
    exit 0
fi

# Support an environment variable for the script directory
if test -n "${BUILDINGSCHEMA_SQLDIR}"; then
    SCRIPTSDIR=${BUILDINGSCHEMA_SQLDIR}
fi

if test ! -f "${SCRIPTSDIR}/sql/buildings/01-create-schema-and-tables.sql"; then
    cat >&2 <<EOF
Cannot find /sql/buildings/01-create-schema-and-tables.sql in ${SCRIPTSDIR}
Please set BUILDINGSCHEMA_SQLDIR environment variable
EOF
    exit 1
fi

DB_NAME=$1; shift

# Check that the target database actually exists
if ! psql -lqt | cut -d \| -f 1 | grep -qw $DB_NAME; then
    echo "Could not find database: ${DB_NAME}" >&2
    exit 1
fi

while [ "$1" != "" ]; do
    PARAM=`echo $1 | awk -F= '{print $1}'`
    case $PARAM in
        --with-test-data)
            WITH_TEST_DATA=true
            ;;
        --with-plugin-setup)
            WITH_PLUGIN_SETUP=true
            ;;
        *)
            # Anything unsupported that follows a valid database name will error out here
            echo "ERROR: Unrecognised option \"$PARAM\""
            usage
            exit 1
            ;;
    esac
    shift
done

export PGDATABASE=$DB_NAME

psql -c "DROP SCHEMA IF EXISTS buildings_lds CASCADE;"
psql -c "DROP SCHEMA IF EXISTS buildings_bulk_load CASCADE;"
psql -c "DROP SCHEMA IF EXISTS buildings CASCADE;"
psql -c "DROP SCHEMA IF EXISTS buildings_common CASCADE"
psql -c "DROP SCHEMA IF EXISTS buildings_reference CASCADE;"

psql -c "CREATE EXTENSION IF NOT EXISTS postgis SCHEMA public;"
# intarray is used in compare_buildings.sql for array sorting
psql -c "CREATE EXTENSION IF NOT EXISTS intarray SCHEMA public;"
psql -c "SET client_min_messages TO WARNING;"

export ON_ERROR_STOP="--set ON_ERROR_STOP=true"

psql_exit() {
    psql_exit_status=$?
    if [ "$psql_exit_status" != "0" ]; then
        exit "$psql_exit_status"
    fi
}

# Execute schema and table files

for s in buildings_common buildings buildings_reference buildings_bulk_load buildings_lds
do
    for file in ${SCRIPTSDIR}/sql/"$s"/*.sql; do
        echo ${file} >&2
        psql -f ${file} $ON_ERROR_STOP
        psql_exit
    done
done

# execute function files

for s in buildings_common buildings buildings_reference buildings_bulk_load buildings_lds
do
    for file in ${SCRIPTSDIR}/sql/"$s"/functions/*.sql; do
        echo ${file} >&2
        psql -f ${file} $ON_ERROR_STOP
        psql_exit
    done
done

# Execute files that create test data - test data remains in database
if [ "${WITH_TEST_DATA}" = true ]; then
    # Execute all files in the test data sql dir
    echo ${SCRIPTSDIR}/tests/testdata/01-insert_test_data_reference.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/01-insert_test_data_reference.sql $ON_ERROR_STOP
    psql_exit
    echo ${SCRIPTSDIR}/tests/testdata/02-insert_test_data_buildings_bulk_load.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/02-insert_test_data_buildings_bulk_load.sql $ON_ERROR_STOP
    psql_exit
    psql -c "SELECT buildings_bulk_load.compare_building_outlines(1);"
    psql -c "SELECT buildings_bulk_load.load_building_outlines(1);"
    psql -c "SELECT buildings_lds.populate_buildings_lds();"
    echo ${SCRIPTSDIR}/tests/testdata/03-insert_test_data_second_dataset.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/03-insert_test_data_second_dataset.sql $ON_ERROR_STOP
    psql_exit
    psql -c "SELECT buildings_bulk_load.compare_building_outlines(2);"
    echo ${SCRIPTSDIR}/tests/testdata/04-insert_test_data_functions.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/04-insert_test_data_functions.sql $ON_ERROR_STOP
    psql_exit
    echo ${SCRIPTSDIR}/tests/testdata/05-insert_test_data_complex.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/05-insert_test_data_complex.sql $ON_ERROR_STOP
    psql_exit
    psql -c "SELECT buildings_bulk_load.compare_building_outlines(4);"

fi
# Execute files that are needed to test the plugin - test data remains in database
if [ "${WITH_PLUGIN_SETUP}" = true ]; then
    # Execute all files in the test data sql dir
    echo ${SCRIPTSDIR}/tests/testdata/01-insert_test_data_reference.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/01-insert_test_data_reference.sql $ON_ERROR_STOP
    psql_exit
    echo ${SCRIPTSDIR}/tests/testdata/06-insert_test_data_buildings_bulk_load_plugin.sql >&2
    psql -f ${SCRIPTSDIR}/tests/testdata/06-insert_test_data_buildings_bulk_load_plugin.sql $ON_ERROR_STOP
    psql_exit
    psql -c "SELECT buildings_bulk_load.compare_building_outlines(2);"

fi
