name: Build docs
on:
  push:
    paths:
      - db/docs/**
jobs:
  docs:
    name: docs
    runs-on: ubuntu-18.04
    env:
      BUILD: docs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install required Python modules
        run: |
          pip3 install Sphinx sphinx_rtd_theme
          pip3 install -r requirements-docs.txt
      - name: Run Sphinx build
        run: |
          sphinx-build -b html db/docs/source db/docs
