name: Run tests
on: push
jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        db_image: [ 'ghcr.io/linz/nz-buildings-db-legacy:v1', 'ghcr.io/linz/nz-buildings-db-modern:v1' ]
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: github
      PGPASSWORD: github
      BASE_DIR: ${{ github.workspace }}
      DB_DOCKER_IMAGE: ${{ matrix.db_image }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Launch database container
        run: |
          bash $BASE_DIR/scripts/steps/launch_database_container.sh
      - name: Print docker logs
        uses: jwalton/gh-docker-logs@v1
      - name: Setup database
        run: |
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/create_test_admin_bdys_schema.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/admin_bdys.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/create_test_aerial_schema.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/aerial_lds.sql
      - name: Sqitch deploy
        run: docker exec --workdir /nz-buildings/db/sql db sqitch deploy --verify
      - name: Sqitch revert
        run: docker exec --workdir /nz-buildings/db/sql db sqitch revert -y
        working-directory: ./db/sql
      - name: Sqitch deploy again
        run: docker exec --workdir /nz-buildings/db/sql db sqitch deploy
        working-directory: ./db/sql
      - name: Add test data
        run: |
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/buildings_reference.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/buildings_common.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/buildings.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/buildings_bulk_load.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/buildings_lds.sql
          docker exec -u postgres db psql -a -f /nz-buildings/db/tests/testdata/db/update_sequences.sql
          docker exec -u postgres db psql -c 'REFRESH MATERIALIZED VIEW buildings_reference.territorial_authority_grid;' 
      - name: Run pgTAP tests
        run: docker exec db pg_prove /nz-buildings/db/tests
