name: Run tests
on: push
jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        db_image: [ 'nz-buildings-db-legacy:2022-07-19_1fc2bb4', 'nz-buildings-db-modern:2022-07-19_1fc2bb4' ]
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: github
      PGPASSWORD: github
      PGDATABASE: github
      PGCONN: postgresql://github:github@localhost:5432/github
      SQITCH_VERSION: 1.2.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Spawn database container
        run: |
          docker run \
          --name db \
          -p 5432:5432 \
          --volume ${{ env.GITHUB_WORKSPACE }}/db/tests:/db_tests \
          --health-cmd pg_isready \
          --health-interval 10s \
          --health-timeout 5s \
          --health-retries 5 \
          -d \
          ghcr.io/linz/${{ matrix.db_image }}
      - name: Install Sqitch 
        run: |
          sudo apt-get install -y libdbd-pg-perl build-essential perl perl-doc
          sudo apt-get install -y cpanminus
          sudo cpanm --notest DWHEELER/App-Sqitch-v${{ env.SQITCH_VERSION }}.tar.gz
      - name: Check Sqitch version
        run: sqitch --version
      - name: Setup database
        run: |
          psql -d $PGCONN -a -f create_test_admin_bdys_schema.sql
          psql -d $PGCONN -a -f db/admin_bdys.sql
          psql -d $PGCONN -a -f create_test_aerial_schema.sql
          psql -d $PGCONN -a -f db/aerial_lds.sql
        working-directory: ./db/tests/testdata
      - name: Sqitch deploy
        run: sqitch deploy --verify
        working-directory: ./db/sql
      - name: Sqitch revert
        run: sqitch revert -y
        working-directory: ./db/sql
      - name: Sqitch deploy again
        run: sqitch deploy
        working-directory: ./db/sql
      - name: Add test data
        run: |
          psql -d $PGCONN -a -f buildings_reference.sql
          psql -d $PGCONN -a -f buildings_common.sql
          psql -d $PGCONN -a -f buildings.sql
          psql -d $PGCONN -a -f buildings_bulk_load.sql
          psql -d $PGCONN -a -f buildings_lds.sql
          psql -d $PGCONN -a -f update_sequences.sql
          psql -c 'REFRESH MATERIALIZED VIEW buildings_reference.territorial_authority_grid;' 
        working-directory: ./db/tests/testdata/db
      - name: Run pgTAP tests
        run: docker exec -it db pg_prove /db_tests
