name: Run tests
on: push
jobs:
  tests:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        db_image: [ 'ghcr.io/linz/nz-buildings-db-legacy:v1', 'ghcr.io/linz/nz-buildings-db-modern:v1' ]
    env:
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: github
      PGPASSWORD: github
      BASE_DIR: ${{ github.workspace }}
      DB_DOCKER_IMAGE: ${{ matrix.db_image }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Launch database container
        run: bash $BASE_DIR/scripts/steps/launch_database_container.sh
      - name: Print docker logs
        uses: jwalton/gh-docker-logs@v1
      - name: Load additional schemas
        run: bash $BASE_DIR/scripts/steps/load_additional_schemas.sh
      - name: Sqitch deploy and verify
        run: bash $BASE_DIR/scripts/steps/sqitch_deploy_verify.sh
      - name: Sqitch revert
        run: bash $BASE_DIR/scripts/steps/sqitch_revert.sh
      - name: Sqitch deploy
        run: bash $BASE_DIR/scripts/steps/sqitch_deploy.sh
      - name: Load test data
        run: bash $BASE_DIR/scripts/steps/load_test_data.sh
      - name: Run pgTAP tests
        run: bash $BASE_DIR/scripts/steps/run_pgtap_tests.sh
